// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: notification.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PushNotificationClient is the client API for PushNotification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushNotificationClient interface {
	// rpc SendNotification (Notification) returns (Response) {}
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*Response, error)
}

type pushNotificationClient struct {
	cc grpc.ClientConnInterface
}

func NewPushNotificationClient(cc grpc.ClientConnInterface) PushNotificationClient {
	return &pushNotificationClient{cc}
}

func (c *pushNotificationClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/notifications.PushNotification/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushNotificationServer is the server API for PushNotification service.
// All implementations should embed UnimplementedPushNotificationServer
// for forward compatibility
type PushNotificationServer interface {
	// rpc SendNotification (Notification) returns (Response) {}
	Subscribe(context.Context, *SubscribeRequest) (*Response, error)
}

// UnimplementedPushNotificationServer should be embedded to have forward compatible implementations.
type UnimplementedPushNotificationServer struct {
}

func (UnimplementedPushNotificationServer) Subscribe(context.Context, *SubscribeRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

// UnsafePushNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushNotificationServer will
// result in compilation errors.
type UnsafePushNotificationServer interface {
	mustEmbedUnimplementedPushNotificationServer()
}

func RegisterPushNotificationServer(s grpc.ServiceRegistrar, srv PushNotificationServer) {
	s.RegisterService(&PushNotification_ServiceDesc, srv)
}

func _PushNotification_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushNotificationServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notifications.PushNotification/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushNotificationServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PushNotification_ServiceDesc is the grpc.ServiceDesc for PushNotification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushNotification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notifications.PushNotification",
	HandlerType: (*PushNotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _PushNotification_Subscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
